### ISSUE TITLE
Suggest mailhog extension to stop actual emails from being sent

### ISSUE THREAD

**Issue by tareiking** [stuartshields/chassis-wordcamp#2]
Not sure whether chassis or chassis-wordcamp related, but after creating a new site - I received an email saying the site was setup.

While this is the expected behaviour on a live site, its unlikely in dev that we want actual emails to be delivered, especially if using an imported database (which could reference live emails), or once you've imported a live wordcamp site (you'd hate to accidentally email any attendees in an import).

I suggest we either include/recommend [chassis mailhog extension](https://github.com/Chassis/MailHog) or disable email sending from the box completely.

**Comment by stuartshields** [comment]
Added mailhog to the readme.
