### ISSUE TITLE
Creating new site via network admin

### ISSUE THREAD

**Issue by tareiking** [stuartshields/chassis-wordcamp#4]
When visiting http://wordcamp.dev/wp-admin/network/site-new.php and adding a new site with the site address structure `2018.cityname`, multisite gives an error `Missing or invalid site address.`.

This could be a core issue as the field description states: `Only lowercase letters (a-z), numbers, and hyphens are allowed.`.

Able to workaround by adding the site as `cityname` > add new site > edit the site > update site url to `2017.cityname.wordcamp.dev`.

**Comment by stuartshields** [comment]
I'll need to look into this more.

**Comment by stuartshields** [comment]
Fixed in #10
