### ISSUE TITLE
Jetpack Contact Forms not activated by default

### ISSUE THREAD

**Issue by cameronjonesweb** [stuartshields/chassis-wordcamp#9]
This causes issues when importing content from an existing WC site, with `invalid post type` errors on import and shortcodes rendering raw. I expect this is an issue with the database dump but perhaps this could be noted in the readme and ideally in the future it would be automatically activated as part of a more automated install process

**Comment by sbshields** [comment]
Ill have a look at this today and see what I come up with.

**Comment by stuartshields** [comment]
### WP Options Importer Plugin enabled

WordPress XML won’t actually export/import options settings. This plugin enables that functionality. I just downloaded that plugin (it’s not being maintained anymore but still works), exported options with contact form activated. then I deactivated the contact form and ran the importer and it enabled the Jetpack contact form for me.

### WP CLI Export
`wp db export test.sql`, deleted site. `wp db import test.sql` imported the site and Jetpack had contact form enabled.

I will keep this issue opened, just incase others come across similar issues and we can debug further.
